/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpenseCategory
 */
export interface ExpenseCategory {
    /**
     * 
     * @type {number}
     * @memberof ExpenseCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseCategory
     */
    color?: string;
}

/**
 * Check if a given object implements the ExpenseCategory interface.
 */
export function instanceOfExpenseCategory(value: object): value is ExpenseCategory {
    return true;
}

export function ExpenseCategoryFromJSON(json: any): ExpenseCategory {
    return ExpenseCategoryFromJSONTyped(json, false);
}

export function ExpenseCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function ExpenseCategoryToJSON(json: any): ExpenseCategory {
    return ExpenseCategoryToJSONTyped(json, false);
}

export function ExpenseCategoryToJSONTyped(value?: ExpenseCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

