/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncomeCategory
 */
export interface IncomeCategory {
    /**
     * 
     * @type {number}
     * @memberof IncomeCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof IncomeCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IncomeCategory
     */
    color?: string;
}

/**
 * Check if a given object implements the IncomeCategory interface.
 */
export function instanceOfIncomeCategory(value: object): value is IncomeCategory {
    return true;
}

export function IncomeCategoryFromJSON(json: any): IncomeCategory {
    return IncomeCategoryFromJSONTyped(json, false);
}

export function IncomeCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function IncomeCategoryToJSON(json: any): IncomeCategory {
    return IncomeCategoryToJSONTyped(json, false);
}

export function IncomeCategoryToJSONTyped(value?: IncomeCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
    };
}

