/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Saving
 */
export interface Saving {
    /**
     * 
     * @type {number}
     * @memberof Saving
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Saving
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof Saving
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Saving
     */
    dateAdded?: Date;
}

/**
 * Check if a given object implements the Saving interface.
 */
export function instanceOfSaving(value: object): value is Saving {
    return true;
}

export function SavingFromJSON(json: any): Saving {
    return SavingFromJSONTyped(json, false);
}

export function SavingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Saving {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'category': json['category'] == null ? undefined : json['category'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'dateAdded': json['dateAdded'] == null ? undefined : (new Date(json['dateAdded'])),
    };
}

export function SavingToJSON(json: any): Saving {
    return SavingToJSONTyped(json, false);
}

export function SavingToJSONTyped(value?: Saving | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'category': value['category'],
        'amount': value['amount'],
        'dateAdded': value['dateAdded'] == null ? undefined : ((value['dateAdded']).toISOString()),
    };
}

